version: "2.3"

services:
  
  ros2-rclgo-pub:
    build: .
    image: ros2/rclgo-foxy
    network_mode: bridge
    entrypoint: /bin/bash -c "cd /go/src/rclgo/rcl && source /opt/ros/foxy/setup.bash && go test -run TestPublisherStringMsg"

  # ros2-rclgo-sub:
  #   build: .
  #   image: ros2/rclgo-foxy
  #   network_mode: bridge
  #   entrypoint: /bin/bash -c "cd /go/src/rclgo/rcl && source /opt/ros/foxy/setup.bash && go test -run TestSubscription"

